import type { Metadata } from "next";
import {
  Architects_Daughter,
  Fredericka_the_Great,
  Geist,
  Geist_Mono,
  Rubik_Doodle_Shadow,
  Rubik_Wet_Paint,
} from "next/font/google";
import "./globals.css";
import { LayoutWithSidebar } from "./layout-with-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const architectsDaughter = Architects_Daughter({
  variable: "--font-architects-daughter",
  subsets: ["latin"],
  weight: ["400"],
});

const rubikDoodleShadow = Rubik_Doodle_Shadow({
  variable: "--font-rubik-doodle-shadow",
  subsets: ["latin"],
  weight: ["400"],
});

const rubikWetPaint = Rubik_Wet_Paint({
  variable: "--font-rubik-wet-paint",
  subsets: ["latin"],
  weight: ["400"],
});

const frederickaTheGreat = Fredericka_the_Great({
  variable: "--font-fredericka-the-great",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${architectsDaughter.variable} ${rubikDoodleShadow.variable} ${rubikWetPaint.variable} ${frederickaTheGreat.variable} antialiased`}
      >
        <LayoutWithSidebar>{children}</LayoutWithSidebar>
      </body>
    </html>
  );
}
